{{- range $.Values.nodes.masters }}
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-{{ .name }}-{{ $.Values.cluster.name }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    cluster-name: {{ $.Values.cluster.name }}-nmstate
spec:
  config:
    interfaces:
      - name: bond0
        type: bond
        state: up
        mtu: 9000
        ipv6:
          enabled: false
        ipv4:
          enabled: false
        link-aggregation:
          mode: active-backup
          options:
            miimon: '150'
            primary: {{ .int1_name | quote }}
          slaves:
          - {{ .int1_name }}
          - {{ .int2_name }}
      - name: bond0.1993
        type: vlan
        state: up
        mtu: 8996
        vlan:
          base-iface: bond0
          id: 1993
        ipv6:
          enabled: false
        ipv4:
          enabled: true
          address:
            - ip: {{ .bond0_IP }}
              prefix-length: 24
          dhcp: false
      - name: {{ .int1_name }}
        type: ethernet
        state: up
        mtu: 9000
        ipv6:
          enabled: false
        ipv4:
          enabled: false
          #dhcp: false
      - name: {{ .int2_name }}
        type: ethernet
        state: ip
        mtu: 9000
        ipv6:
          enabled: false
        ipv4:
          enabled: false
          #dhcp: false
    dns-resolver:
      config:
        server:
          - '{{ $.Values.global.dns }}'
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: {{ $.Values.cluster.default_router }}
          next-hop-interface: bond0
  interfaces:
    - name: {{ .int1_name | quote }}
      macAddress: {{ .int1_mac | quote }}
    - name: {{ .int2_name | quote }}
      macAddress: {{ .int2_mac | quote }}
---
{{- end }}
